version: '3'
services:
  web:
    image: smnf/chantlab
    build: .
    ports:
      - "80:8001"
    volumes:
      - /opt/chantlab/storage:/opt/chantlab/storage
    depends_on:
      - migration
  migration:
    image: smnf/chantlab
    build: .
    command: /opt/chantlab/chantlab-deploy-venv/bin/python /opt/chantlab/chantlab_deploy/modules/chantlab_backend/manage.py migrate --noinput
    volumes:
      - /opt/chantlab/storage:/opt/chantlab/storage
