[program:chantlab_backend]
command=/opt/run_chantlab_backend.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/run_chantlab_backend.err.log
stdout_logfile=/var/log/run_chantlab_backend.out.log
