[program:chantlab_frontend]
command=/opt/run_chantlab_frontend.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/run_chantlab_frontend.err.log
stdout_logfile=/var/log/run_chantlab_frontend.out.log
